id: P004172
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:58:11.840082
source_metadata:
  id: bdr:W25589
  title: ནམ་མཁའ་རྒྱལ་མཚན་གྱི་ཕྱི་རྣམ་ཐར་འབྲིང་པོ
  author: ''
  volumes:
    9c704e09f8de416fa9f7e21292be56c8:
      image_group_id: I1KG3769
      title: ''
      volume_number: 1
      total_pages: 40
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
