id: IA606B188
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T10:10:50+00:00'
last_modified: '2022-06-07T20:47:31.894966+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25589
  title: ནམ་མཁའ་རྒྱལ་མཚན་གྱི་ཕྱི་རྣམ་ཐར་འབྲིང་པོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C0A5:
      image_group_id: I1KG3769
      title: ''
      total_pages: 40
      order: 1
      base_file: C0A5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
